export const question_data = [
    { "question": "What is the speed of light", "subject": "Physics", "topic": "Waves", "difficulty": "Easy", "marks": 5 },
    { "question": "Define Newton's First Law", "subject": "Physics", "topic": "Mechanics", "difficulty": "Medium", "marks": 10 },
    { "question": "Solve for x: 2x + 5 = 15", "subject": "Mathematics", "topic": "Algebra", "difficulty": "Medium", "marks": 10 },
    { "question": "Explain the process of photosynthesis", "subject": "Biology", "topic": "Botany", "difficulty": "Hard", "marks": 15 },
    { "question": "Who wrote 'Romeo and Juliet'", "subject": "Literature", "topic": "Shakespeare", "difficulty": "Easy", "marks": 5 },
    { "question": "What is the capital of France", "subject": "Geography", "topic": "Countries", "difficulty": "Hard", "marks": 15 },
    { "question": "Describe the structure of a cell", "subject": "Biology", "topic": "Cell Biology", "difficulty": "Medium", "marks": 10 },
    { "question": "Solve for y: 3y - 7 = 20", "subject": "Mathematics", "topic": "Algebra", "difficulty": "Easy", "marks": 5 },
    { "question": "Name three programming languages", "subject": "Computer Science", "topic": "Programming", "difficulty": "Easy", "marks": 5 },
    { "question": "What is the Pythagorean theorem", "subject": "Mathematics", "topic": "Geometry", "difficulty": "Medium", "marks": 10 },
    { "question": "Who discovered penicillin", "subject": "Biology", "topic": "Medicine", "difficulty": "Hard", "marks": 15 },
    { "question": "What is the capital of Japan", "subject": "Geography", "topic": "Countries", "difficulty": "Medium", "marks": 10 },
    { "question": "Name a famous novel by George Orwell", "subject": "Literature", "topic": "Novels", "difficulty": "Easy", "marks": 5 },
    { "question": "What is the boiling point of water?", "subject": "Chemistry", "topic": "Physical Chemistry", "difficulty": "Easy", "marks": 5 },
    { "question": "Who is known as the 'Father of Computer Science'?", "subject": "Computer Science", "topic": "History of Computing", "difficulty": "Medium", "marks": 10 },
    { "question": "Solve the integral: ∫(2x + 3)dx", "subject": "Mathematics", "topic": "Calculus", "difficulty": "Hard", "marks": 15 },
    { "question": "Name the three branches of the U.S. government", "subject": "Political Science", "topic": "Government", "difficulty": "Medium", "marks": 10 },
    { "question": "Who painted the Mona Lisa?", "subject": "Art", "topic": "Painting", "difficulty": "Easy", "marks": 5 },
    { "question": "What is the primary function of the kidneys?", "subject": "Biology", "topic": "Human Anatomy", "difficulty": "Hard", "marks": 15 },
    { "question": "Which planet is known as the 'Red Planet'?", "subject": "Astronomy", "topic": "Planets", "difficulty": "Easy", "marks": 5 },
    { "question": "Who wrote 'To Kill a Mockingbird'?", "subject": "Literature", "topic": "Novels", "difficulty": "Medium", "marks": 10 },
    { "question": "What is the main component of Earth's atmosphere?", "subject": "Geography", "topic": "Atmosphere", "difficulty": "Hard", "marks": 15 },
    { "question": "Define the concept of 'Supply and Demand' in Economics", "subject": "Economics", "topic": "Microeconomics", "difficulty": "Medium", "marks": 10 },
    { "question": "Who discovered the theory of relativity?", "subject": "Physics", "topic": "Modern Physics", "difficulty": "Hard", "marks": 15 },
    { "question": "List the top three industrial revolutions", "subject": "History", "topic": "Industrial Revolutions", "difficulty": "Easy", "marks": 5 }  
];